services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 5

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=testdb
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
